kubaceg_sylius_paynow_plugin_notify:
  path: /payment/paynow/notify
  methods: [POST]
  defaults:
    _controller: kubaceg_sylius_paynow_plugin.controller.notify:notifyAction

kubaceg_sylius_paynow_plugin_success:
  path: /payment/paynow/success
  methods: [GET]
  defaults:
    _controller: kubaceg_sylius_paynow_plugin.controller.success:successAction
